name: build workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build (iOS + watchOS)
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - scheme: mirroringBooth
            platform: iOS Simulator
            device_regex: "iPhone.*\\(17\\.[0-9]+\\)"
            device_fallback_regex: "iPhone [0-9]+"
          - scheme: mirroringBoothWatch
            platform: watchOS Simulator
            os_major: "10"
            device_regex: "Apple Watch.*\\(10\\.[0-9]+\\)"
            device_fallback_regex: "Apple Watch"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint (no warnings, no errors)
        working-directory: mirroringBooth
        run: |
          set -euo pipefail
          # --strict: warning도 exit code != 0로 처리해서 CI에서 실패하게 함
          swiftlint lint --strict --config .swiftlint.yml

      - name: Select Simulator
        working-directory: mirroringBooth
        env:
          PLATFORM: ${{ matrix.platform }}
          DEVICE_REGEX: ${{ matrix.device_regex }}
          DEVICE_FALLBACK_REGEX: ${{ matrix.device_fallback_regex }}
        run: |
          set -euo pipefail

          echo "Searching for simulator matching: ${DEVICE_REGEX}"
          device=$(xcrun simctl list devices available | \
            grep -E "${DEVICE_REGEX}" | \
            head -1 | \
            sed -E 's/[[:space:]]*([^(]+).*/\1/' | \
            sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

          if [ -z "${device}" ]; then
            echo "⚠️ No exact match found. Falling back to: ${DEVICE_FALLBACK_REGEX}"
            device=$(xcrun simctl list devices available | \
              grep -E "${DEVICE_FALLBACK_REGEX}" | \
              head -1 | \
              sed -E 's/[[:space:]]*([^(]+).*/\1/' | \
              sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          fi

          if [ -z "${device}" ]; then
            echo "❌ No simulator found for platform ${PLATFORM}"
            exit 1
          fi

          echo "✅ Using simulator: ${device}"
          echo "device=${device}" >> "$GITHUB_OUTPUT"
        id: sim

      - name: Build
        working-directory: mirroringBooth
        env:
          SCHEME: ${{ matrix.scheme }}
          PLATFORM: ${{ matrix.platform }}
          DEVICE: ${{ steps.sim.outputs.device }}
        run: |
          set -euo pipefail

          echo "Scheme: ${SCHEME}"
          echo "Destination: platform=${PLATFORM},name=${DEVICE}"

          xcodebuild build \
            -scheme "${SCHEME}" \
            -project "mirroringBooth.xcodeproj" \
            -destination "platform=${PLATFORM},name=${DEVICE}"
